Feature/lynguyxn/chess draw handler
TritonSE/YSC-Mobile-Application pull request #27
Opened 2022-04-30 01:48 UTC by Miyuki-L

### Administrative Info
[GitHub Issue #]
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Added draw button to chess screen
- Handled proposing and receiving draw request in the frontend
- Handled accepting and rejecting draw request in the frontend

### Testing
How did you confirm your changes worked? 
- Tested sending and receiving draw request on two devices
- Tested accepting and rejecting draw request on two devices

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| Chess Screen with Draw Button |
| --- |
|<img src="https://user-images.githubusercontent.com/59126064/166085750-75b63b49-d0ab-4bc3-813d-2961dd05f841.png" width="300px"/>  |

| Draw Request Received Popup |
| --- |
| <img src="https://user-images.githubusercontent.com/59126064/166085800-768daf44-d0db-44c6-afce-85458567967c.png" width="300px"/>  |

2022-05-10 00:51 UTC, RyanHUNGry requested changes

2022-05-10 00:51 UTC, RyanHUNGry commented on mobile/src/components/popups/popup_templates/OneButtonPopup.tsx
> +import { Alert, Modal, Text, Pressable, View } from "react-native";
In my popup PR, I moved this template one directory up and removed the popup_templates directory so you guys will have to do the sameand all connected import statements to match this change.

2022-05-10 00:51 UTC, RyanHUNGry commented on mobile/src/components/popups/popup_templates/TwoButtonPopup.tsx
> +import { Alert, Modal, Text, Pressable, View } from "react-native";
Same thing here with directory change

2022-05-10 00:51 UTC, RyanHUNGry commented on mobile/src/screens/Chess.tsx
> +import OneButtonPopup from "../components/popups/popup_templates/OneButtonPopup";
change to "../components/popups/OneButtonPopup"

2022-05-10 00:51 UTC, RyanHUNGry commented on mobile/src/screens/Chess.tsx
> +import TwoButtonPopup from "../components/popups/popup_templates/TwoButtonPopup";
change to "../components/popups/TwoButtonPopup"

2022-05-16 02:32 UTC, lynguyxn commented on mobile/src/components/popups/popup_templates/OneButtonPopup.tsx
> +import { Alert, Modal, Text, Pressable, View } from "react-native";
resolved

2022-05-16 15:46 UTC, nicolaswl approved these changes
LGTM

2022-05-16 15:46 UTC, nicolaswl commented on backend/src/eventHandlers/drawHandler.ts
> +    console.log("proposing draw received");
Remove the log statement if it was just used for debugging

2022-05-16 18:44 UTC, lynguyxn commented on backend/src/eventHandlers/drawHandler.ts
> +    console.log("proposing draw received");
already removed in latest version

2022-05-18 03:51 UTC, RyanHUNGry approved these changes

2022-05-18 04:00 UTC, merged